### PR TITLE
Revise styles

### PR DESCRIPTION
**Pull request by doctor-g**
There are now two styles for use with in-game text: 'text' for regular text and 'bigtext' for bigger text. The sizes of these are specified in shared-styles. This matches the visual design that @lnt614 had built in, but with a slightly more sane application architecture (I mean, it's still CSS after all).

### CODE REVIEW

**Review by drsiscoe — COMMENTED** [review]
I have only one question:

In the root of shared-styles, both primary and secondary font color are the exact same color. Is it reasonable to do away with secondary font color then since it is the same as primary?

**Comment by doctor-g** [comment]
Good question. It looks like secondary-font-color _is_ actually used in our custom `paper-button` style. I am guessing this came from some sample polymer code. Do we want to add a different dark tone to the palette (or use what we already have) to define the secondary color and see how those buttons look? I was really more interested in just fixing the leading in this PR, but there's no reason we couldn't do some other beautification while we're here.

**Comment by doctor-g** [comment]
@drsiscoe I put in a muddy gray-green (3d4a36) as a secondary color, and I think it looks fine. It's almost imperceptible, the difference between this and black, so maybe it's just hopeful design. Let me know what you think.

**Comment by drsiscoe** [comment]
I guess I was thinking of it as more of a DRY violation. Why define the same color twice when you could define it once and just keep using the primary color instead of having it unnecessarily defined twice ? 

I'd have to agree it's similar to black, but there is some noticeable difference between the two (to my eyes at least). So, it seems okay to me. I guess it doesn't feel like it has an overall impact on the design. (Because feelings are important?)

**Comment by drsiscoe** [comment]
I'm happy to merge this as it is now, though.

**Comment by doctor-g** [comment]
Part of my rationale was that if we did copy this from an existing paper-button example, maybe the good material designers at Google decided that this color should be a secondary one not a primary one. I mean, it's a stretch, so we could go either way. I'll leave the ball in your court.

**Pull request merged**
