### PR TITLE
Bind checked attribute to selected property

### PR DESCRIPTION
**Pull request by grevers**
@doctor-g This branch makes a single change in the checklist view. Tests may need to be added to assert that this is a solution to issue #27 .

### CODE REVIEW

**Comment by doctor-g** [comment]
@grevers Sounds backwards: the tests should be written first to verify the broken behavior, then you know you fixed it when the tests pass!

**Comment by doctor-g** [comment]
This seems to work, but there's a funny dependency between the tap listener and the data binding. By default the map data does not have a `selected` field for each response. We could add that, but it would be a drag. Without it, the tap listener currently adds that element, which is then bound. Before it exists, the binding is to nothing, so removing the tap listener---which appears redundant because of the binding---makes several tests fail.

**Comment by doctor-g** [comment]
@grevers I removed your change and created a test that verifies the bad behavior. Then putting your change back in, I could show that it worked. I also ran manual integration testing to verify. No change was required in `map-data`. I would be more comfortable if you could try this yourself too, of course.

We definitely want to squash the commits together since otherwise the test doesn't show up until after the fix, but they should really go together. The commit comment should be edited for consistency too, so that it doesn't read like the test is part of a separate chunk.

**Comment by grevers** [comment]
@doctor-g The commit comment that should be edited you are referring to is the first comment in this thread, correct?

**Comment by doctor-g** [comment]
@grevers I was responding to a phenomenon I have seen several times where people approve a pull request on a branch with several commits, and then just use the default commit comment, which is a chronological listing of the individual commit messages. That's actually quite bad practice, since not all those commit messages are necessary, and worse, they may not actually describe what the commit is all about. Refer to https://github.com/erlang/otp/wiki/Writing-good-commit-messages for the tips---just because a commit message is part of a PR doesn't mean we should be changing protocol.

**Comment by grevers** [comment]
@doctor-g So I have been looking at your [commit message](https://github.com/spring2017gamestudio/prairie-creek/commit/5fe6a3339e3a6db5e0a602d342c33a734a9c0c0b ). I don't want to use the default commit comment. I want to know the commands to create a succinct commit comment like yours. Do I need to amend [my initial commit](https://github.com/spring2017gamestudio/prairie-creek/commit/055ded950d907ae9a14b92d05f367c65eeaab9a4)?

**Comment by doctor-g** [comment]
When you choose to squash the merge, it will give you a text area where your can specify the commit message

**Pull request merged**
