### PR TITLE
New creek area

### PR DESCRIPTION
**Pull request by dmwisenberg**
Implements the playable area around the reservoir. The area is a circle, with the center point being in the middle of the marked sites, and the area's radius is large enough that it should not be an issue.

### CODE REVIEW

**Comment by dakotamalchow** [comment]
The inPlayableRange by default set to true. Would this ever have the chance of using that default before calculating the actual result? I'm just wondering if it would be safer to set it to false in case of some flook, but if it calls the determine function every time then it should be fine.

**Comment by dmwisenberg** [comment]
Dakota, 
The determine function should be called every time, from what I understand. I don't think it should be an issue. If you want to change that then commit and push again I would be fine with that as well.

**Comment by doctor-g** [comment]
I checked out the branch and served it locally, but running the game, I don't see anything different: I show up at my location (home), no dialog box or anything. Looking at `prairie-creek-game`, it looks like `playable-area` is not integrated.

**Comment by dakotamalchow** [comment]
Dr. G,
The playable area does not have a view, similar to how current site does not have a view. David and I will each make view, one for when the player starts the game outside of the playable area and one for when the player starts inside, but then leaves while in game play. Unless if you think that these two views should be combined into one, we planned on using playable-area in each of these views.

**Comment by doctor-g** [comment]
I wouldn't merge, or even open a PR on it yet, then, if it's not a complete feature. This is like the case with #101. It doesn't make sense to review it until the feature is integrated and ready to go.

You might think about how this would integrate with title-view, especially with respect to the work I was just putting in on #108. You are referencing what sounds like new views above, but it's not clear to me that it's what we need to get people started. We might be better off with something simple like a paragraph, "Go to prairie creek park to start the game! Click here for directions!" that shows up on `title-view`. #108 disables the play button until we have any kind of signal, but these handful of ideas could be connected together.

**Pull request closed without merging**
